# Generated by Django 6.0.2 on 2026-02-25 17:09

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("scanner", "0001_initial"),
    ]

    operations = [
        migrations.CreateModel(
            name="ScanHistory",
            fields=[
                (
                    "id",
                    models.BigAutoField(
                        auto_created=True,
                        primary_key=True,
                        serialize=False,
                        verbose_name="ID",
                    ),
                ),
                ("barcode", models.CharField(max_length=50)),
                (
                    "product_name",
                    models.CharField(blank=True, max_length=255, null=True),
                ),
                ("scanned_at", models.DateTimeField(auto_now_add=True)),
            ],
        ),
    ]
