# Generated by Django 6.0.2 on 2026-02-26 10:29

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ("scanner", "0002_scanhistory"),
    ]

    operations = [
        migrations.DeleteModel(
            name="ScanHistory",
        ),
    ]
