# Generated by Django 6.0.2 on 2026-02-26 12:10

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("scanner", "0003_delete_scanhistory"),
    ]

    operations = [
        migrations.CreateModel(
            name="Scanhistory",
            fields=[
                (
                    "id",
                    models.BigAutoField(
                        auto_created=True,
                        primary_key=True,
                        serialize=False,
                        verbose_name="ID",
                    ),
                ),
                ("barcode", models.CharField(max_length=50)),
                ("name", models.CharField(blank=True, max_length=255, null=True)),
                ("scanned_qty", models.IntegerField(default=1)),
                ("scanned_at", models.DateTimeField(auto_now_add=True)),
            ],
        ),
    ]
