# Generated by Django 6.0.2 on 2026-02-26 13:35

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("scanner", "0004_scanhistory"),
    ]

    operations = [
        migrations.AlterField(
            model_name="scanhistory",
            name="scanned_qty",
            field=models.IntegerField(),
        ),
    ]
