# Generated by Django 5.2.11 on 2026-03-03 13:49

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("scanner", "0005_alter_scanhistory_scanned_qty"),
    ]

    operations = [
        migrations.RenameField(
            model_name="product",
            old_name="qty",
            new_name="required_qty",
        ),
        migrations.RenameField(
            model_name="scanhistory",
            old_name="scanned_qty",
            new_name="available_qty",
        ),
        migrations.RenameField(
            model_name="scanhistory",
            old_name="scanned_at",
            new_name="scan_time",
        ),
        migrations.AddField(
            model_name="scanhistory",
            name="required_qty",
            field=models.IntegerField(default=0),
            preserve_default=False,
        ),
        migrations.AlterField(
            model_name="product",
            name="barcode",
            field=models.CharField(max_length=100, unique=True),
        ),
        migrations.AlterField(
            model_name="product",
            name="id",
            field=models.AutoField(
                auto_created=True, primary_key=True, serialize=False, verbose_name="ID"
            ),
        ),
        migrations.AlterField(
            model_name="scanhistory",
            name="barcode",
            field=models.CharField(max_length=100),
        ),
        migrations.AlterField(
            model_name="scanhistory",
            name="id",
            field=models.AutoField(
                auto_created=True, primary_key=True, serialize=False, verbose_name="ID"
            ),
        ),
        migrations.AlterField(
            model_name="scanhistory",
            name="name",
            field=models.CharField(default="Unknown", max_length=255),
            preserve_default=False,
        ),
    ]
